version: 2

sources:
  - name: raw
    schema: raw_data_circle
    description: raw data from cirlce sportswear
    tables:
      - name: sales
        identifier: raw_cc_sales
        description: sales data from circle
      - name: stock
        identifier: raw_cc_stock
        description: stock check from circle 

models:
  - name: stg_raw__stock
    description: cleaning of raw stock
  - name: stg_raw__sales
    description: cleaning of raw sales data
  - name: int_stock_sales
    description: combination of sales and stock
  - name: int_stock_sales_by_product
    description: sales by product